{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "niuu.fullname" . }}
  labels:
    {{- include "niuu.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .routes }}
          - path: {{ .path }}
            pathType: {{ .pathType | default "Prefix" }}
            backend:
              service:
                name: {{ include "niuu.ingressServiceName" (dict "root" $ "service" .service) }}
                port:
                  {{- if .portName }}
                  name: {{ .portName }}
                  {{- else if .portNumber }}
                  number: {{ .portNumber }}
                  {{- else }}
                  name: http
                  {{- end }}
          {{- end }}
    {{- end }}
{{- end }}
