"""Resident long-horizon work management V0."""

from __future__ import annotations

from .adapters import (
    LocalCapabilityDiscoveryBackend,
    LocalResidentWorkItemBackend,
    LocalSimulatedResidentExecutor,
    LocalSubprocessResidentExecutor,
    WorkflowResidentExecutionAdapter,
)
from .config import (
    ResidentAutonomyLoopConfig,
    ResidentCapabilityDiscoveryConfig,
    ResidentDelegationConfig,
    ResidentPortfolioConfig,
    ResidentPortfolioEvidence,
    ResidentPortfolioStewardConfig,
    WakefulRuntimePort,
)
from .constants import (
    _CAPABILITY_DISCOVERY_PREFIX,
    _DECISION_PREFIX,
    _DELEGATION_PREFIX,
    _DELEGATION_RESULT_PREFIX,
    _DELEGATION_REVIEW_PREFIX,
    _OBJECTIVE_PREFIX,
    _OPERATOR_CONTACT_PREFIX,
    _PORTFOLIO_PATH,
)
from .helpers import (
    _merge_text,
    _parse_delegation,
    _parse_objective,
    _parse_portfolio,
    _render_delegation,
    _render_list,
    _render_objective,
    _render_operator_contact,
    _render_portfolio,
    build_worker_brief,
    detect_capability_gaps,
    discover_objectives,
    merge_objectives,
    prioritize_objectives,
    render_capability_discovery_result,
    render_steward_report,
    render_validation_report,
    review_delegation_result,
    select_delegation_candidates,
    select_objectives,
)
from .runtimes import (
    ResidentAutonomyLoopRuntime,
    ResidentCapabilityDiscoveryRuntime,
    ResidentDelegationRuntime,
    ResidentLongHorizonWorkManager,
    ResidentPortfolioStewardRuntime,
    ResidentPortfolioValidator,
)

__all__ = [
    "_CAPABILITY_DISCOVERY_PREFIX",
    "_DECISION_PREFIX",
    "_DELEGATION_PREFIX",
    "_DELEGATION_RESULT_PREFIX",
    "_DELEGATION_REVIEW_PREFIX",
    "_OBJECTIVE_PREFIX",
    "_OPERATOR_CONTACT_PREFIX",
    "_PORTFOLIO_PATH",
    "_merge_text",
    "_parse_delegation",
    "_parse_objective",
    "_parse_portfolio",
    "_render_delegation",
    "_render_list",
    "_render_objective",
    "_render_operator_contact",
    "_render_portfolio",
    "LocalCapabilityDiscoveryBackend",
    "LocalResidentWorkItemBackend",
    "LocalSimulatedResidentExecutor",
    "LocalSubprocessResidentExecutor",
    "WorkflowResidentExecutionAdapter",
    "ResidentAutonomyLoopConfig",
    "ResidentAutonomyLoopRuntime",
    "ResidentCapabilityDiscoveryConfig",
    "ResidentCapabilityDiscoveryRuntime",
    "ResidentDelegationConfig",
    "ResidentDelegationRuntime",
    "ResidentLongHorizonWorkManager",
    "ResidentPortfolioConfig",
    "ResidentPortfolioEvidence",
    "ResidentPortfolioStewardConfig",
    "ResidentPortfolioStewardRuntime",
    "ResidentPortfolioValidator",
    "WakefulRuntimePort",
    "build_worker_brief",
    "detect_capability_gaps",
    "discover_objectives",
    "merge_objectives",
    "prioritize_objectives",
    "render_capability_discovery_result",
    "render_steward_report",
    "render_validation_report",
    "review_delegation_result",
    "select_delegation_candidates",
    "select_objectives",
]
