{{- if and (not .Values.database.existingSecret) .Values.database.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "niuu-shared.databaseSecretName" . }}
  labels:
    {{- include "niuu-shared.labels" . | nindent 4 }}
  {{- with .Values.database.secretAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{ .Values.database.userKey | default "username" }}: {{ .Values.database.username | quote }}
  {{ .Values.database.passwordKey | default "password" }}: {{ .Values.database.password | quote }}
  {{- with .Values.database.extraSecretData }}
  {{- range $key, $value := . }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
{{- end }}
